# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.clock = QtWidgets.QLabel(parent=self.centralwidget)
        self.clock.setEnabled(True)
        self.clock.setGeometry(QtCore.QRect(330, 50, 340, 160))
        font = QtGui.QFont()
        font.setPointSize(100)
        self.clock.setFont(font)
        self.clock.setAutoFillBackground(False)
        self.clock.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.clock.setObjectName("clock")
        self.btn_to_calendar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_to_calendar.setGeometry(QtCore.QRect(100, 350, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.btn_to_calendar.setFont(font)
        self.btn_to_calendar.setObjectName("btn_to_calendar")
        self.btn_to_weather = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_to_weather.setGeometry(QtCore.QRect(600, 350, 300, 100))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.btn_to_weather.setFont(font)
        self.btn_to_weather.setObjectName("btn_to_weather")
        self.btn_register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_register.setGeometry(QtCore.QRect(860, 5, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.btn_register.setFont(font)
        self.btn_register.setObjectName("btn_register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main window"))
        self.clock.setText(_translate("MainWindow", "12:00"))
        self.btn_to_calendar.setText(_translate("MainWindow", "Календарь"))
        self.btn_to_weather.setText(_translate("MainWindow", "Погода"))
        self.btn_register.setText(_translate("MainWindow", "Sign up"))
