# Form implementation generated from reading ui file 'weather_withoutUser.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_WithoutUser(object):
    def setupUi_withoutUser(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 200, 500, 200))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("background: rgb(115, 115, 173);\n"
"border-radius: 8px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.btn_home = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_home.setGeometry(QtCore.QRect(885, 12, 50, 50))
        self.btn_home.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_home.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setStyleSheet("border: 4px solid;\n"
"border-color: rgb(190, 190, 213);\n"
"border-radius: 8px;")
        self.btn_home.setText("")
        self.btn_home.setIcon(QtGui.QIcon('items\icons\home.png'))
        self.btn_home.setIconSize(QtCore.QSize(50, 50))
        self.btn_home.setObjectName("btn_home")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi_withoutUser(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi_withoutUser(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "weather"))
        self.label.setText(_translate("MainWindow", "Войдите в аккаунт"))
