# Form implementation generated from reading ui file 'weather.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 600))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.today_weather = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.today_weather.setFont(font)
        self.today_weather.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.today_weather.setObjectName("today_weather")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.today_weather)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.frame = QtWidgets.QFrame(parent=self.today_weather)
        self.frame.setStyleSheet("background: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border: 4px solid rgb(190, 190, 213);")
        self.frame.setObjectName("frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_13.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, -1, 10, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.city = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.city.setFont(font)
        self.city.setStyleSheet("background: rgb(255, 255, 255, 0);\n"
"max-height: 50px;\n"
"font-size: 30px;\n"
"font: bold;\n"
"border: 0px;\n"
"padding-left: 20px;")
        self.city.setObjectName("city")
        self.horizontalLayout_17.addWidget(self.city)
        self.btn_home = QtWidgets.QPushButton(parent=self.frame)
        self.btn_home.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_home.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../items/icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon)
        self.btn_home.setIconSize(QtCore.QSize(50, 50))
        self.btn_home.setObjectName("btn_home")
        self.horizontalLayout_17.addWidget(self.btn_home)
        self.verticalLayout_13.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, -1, 400, -1)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.temp = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.temp.setFont(font)
        self.temp.setStyleSheet("border: 0px;\n"
"padding-left: 100px;\n"
"color: rgb(113, 113, 170);")
        self.temp.setObjectName("temp")
        self.horizontalLayout_13.addWidget(self.temp)
        self.weather_icon_5 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.weather_icon_5.setFont(font)
        self.weather_icon_5.setStyleSheet("border: 0px;")
        self.weather_icon_5.setText("")
        self.weather_icon_5.setPixmap(QtGui.QPixmap("../01d@2x.png"))
        self.weather_icon_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon_5.setObjectName("weather_icon_5")
        self.horizontalLayout_13.addWidget(self.weather_icon_5)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.weather = QtWidgets.QLabel(parent=self.frame)
        self.weather.setStyleSheet("background: rgb(105, 105, 157, 0.7);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"border: 0px;\n"
"padding-left: 20px;\n"
"font: 20px;")
        self.weather.setObjectName("weather")
        self.verticalLayout_12.addWidget(self.weather)
        self.temp_like = QtWidgets.QLabel(parent=self.frame)
        self.temp_like.setStyleSheet("background: rgb(105, 105, 157, 0.5);\n"
"border-top-left-radius: 0px;\n"
"border-top-right-radius: 0px;\n"
"border: 0px;\n"
"padding-left: 20px;\n"
"font: 15px;")
        self.temp_like.setObjectName("temp_like")
        self.verticalLayout_12.addWidget(self.temp_like)
        self.horizontalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 400, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.wind = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.wind.setFont(font)
        self.wind.setStyleSheet("border: 0px;\n"
"padding-left: 20px;")
        self.wind.setObjectName("wind")
        self.horizontalLayout_14.addWidget(self.wind)
        self.humidity = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.humidity.setFont(font)
        self.humidity.setStyleSheet("border: 0px;")
        self.humidity.setObjectName("humidity")
        self.horizontalLayout_14.addWidget(self.humidity)
        self.pressure = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pressure.setFont(font)
        self.pressure.setStyleSheet("border: 0px;")
        self.pressure.setObjectName("pressure")
        self.horizontalLayout_14.addWidget(self.pressure)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15.addWidget(self.frame)
        self.verticalLayout.addWidget(self.today_weather)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.weathe_tomorrow = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.weathe_tomorrow.setFont(font)
        self.weathe_tomorrow.setStyleSheet("border-radius: 8px;\n"
"background: rgba(115, 115, 173, 0.4);\n"
"")
        self.weathe_tomorrow.setObjectName("weathe_tomorrow")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.weathe_tomorrow)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 70)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.day_of_week_1 = QtWidgets.QLabel(parent=self.weathe_tomorrow)
        self.day_of_week_1.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"max-height: 50px;\n"
"font-size: 20px;\n"
"font: bold;")
        self.day_of_week_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.day_of_week_1.setObjectName("day_of_week_1")
        self.horizontalLayout_3.addWidget(self.day_of_week_1)
        self.date_1 = QtWidgets.QLabel(parent=self.weathe_tomorrow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_1.setFont(font)
        self.date_1.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"max-height: 40px;\n"
"padding-bottom: 10px;")
        self.date_1.setObjectName("date_1")
        self.horizontalLayout_3.addWidget(self.date_1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.weather_icon_1 = QtWidgets.QLabel(parent=self.weathe_tomorrow)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.weather_icon_1.setFont(font)
        self.weather_icon_1.setStyleSheet("background: rgb(255, 255, 255, 0);")
        self.weather_icon_1.setText("")
        self.weather_icon_1.setPixmap(QtGui.QPixmap("../01d@2x.png"))
        self.weather_icon_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon_1.setObjectName("weather_icon_1")
        self.horizontalLayout_4.addWidget(self.weather_icon_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.temp_day_1 = QtWidgets.QLabel(parent=self.weathe_tomorrow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temp_day_1.setFont(font)
        self.temp_day_1.setStyleSheet("background: rgb(255, 255, 255, 0.6);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.temp_day_1.setObjectName("temp_day_1")
        self.verticalLayout_2.addWidget(self.temp_day_1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.weather_1 = QtWidgets.QLabel(parent=self.weathe_tomorrow)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weather_1.setFont(font)
        self.weather_1.setStyleSheet("background: rgb(255, 255, 255, 0);\n"
"max-height: 30px;\n"
"color: rgb(255, 255, 255);\n"
"font: 15px;\n"
"")
        self.weather_1.setObjectName("weather_1")
        self.verticalLayout_3.addWidget(self.weather_1)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout.addWidget(self.weathe_tomorrow)
        self.widget_days_2 = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.widget_days_2.setFont(font)
        self.widget_days_2.setStyleSheet("border-radius: 8px;\n"
"background: rgba(115, 115, 173, 0.6);\n"
"")
        self.widget_days_2.setObjectName("widget_days_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_days_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(-1, -1, -1, 70)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.day_of_week_2 = QtWidgets.QLabel(parent=self.widget_days_2)
        self.day_of_week_2.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"max-height: 50px;\n"
"font-size: 20px;\n"
"font: bold;")
        self.day_of_week_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.day_of_week_2.setObjectName("day_of_week_2")
        self.horizontalLayout_5.addWidget(self.day_of_week_2)
        self.date_2 = QtWidgets.QLabel(parent=self.widget_days_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_2.setFont(font)
        self.date_2.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"max-height: 40px;\n"
"padding-bottom: 10px;")
        self.date_2.setObjectName("date_2")
        self.horizontalLayout_5.addWidget(self.date_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.weather_icon_2 = QtWidgets.QLabel(parent=self.widget_days_2)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.weather_icon_2.setFont(font)
        self.weather_icon_2.setStyleSheet("background: rgb(255, 255, 255, 0);")
        self.weather_icon_2.setText("")
        self.weather_icon_2.setPixmap(QtGui.QPixmap("../01d@2x.png"))
        self.weather_icon_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon_2.setObjectName("weather_icon_2")
        self.horizontalLayout_6.addWidget(self.weather_icon_2)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.temp_day_2 = QtWidgets.QLabel(parent=self.widget_days_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temp_day_2.setFont(font)
        self.temp_day_2.setStyleSheet("background: rgb(255, 255, 255, 0.6);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.temp_day_2.setObjectName("temp_day_2")
        self.verticalLayout_5.addWidget(self.temp_day_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.weather_2 = QtWidgets.QLabel(parent=self.widget_days_2)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weather_2.setFont(font)
        self.weather_2.setStyleSheet("background: rgb(255, 255, 255, 0);\n"
"max-height: 30px;\n"
"color: rgb(255, 255, 255);\n"
"font: 15px;\n"
"")
        self.weather_2.setObjectName("weather_2")
        self.verticalLayout_6.addWidget(self.weather_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout.addWidget(self.widget_days_2)
        self.widget_days_3 = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.widget_days_3.setFont(font)
        self.widget_days_3.setStyleSheet("border-radius: 8px;\n"
"background: rgba(115, 115, 173, 0.8);\n"
"")
        self.widget_days_3.setObjectName("widget_days_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_days_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 70)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.day_of_week_3 = QtWidgets.QLabel(parent=self.widget_days_3)
        self.day_of_week_3.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"max-height: 50px;\n"
"font-size: 20px;\n"
"font: bold;")
        self.day_of_week_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.day_of_week_3.setObjectName("day_of_week_3")
        self.horizontalLayout_8.addWidget(self.day_of_week_3)
        self.date_3 = QtWidgets.QLabel(parent=self.widget_days_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_3.setFont(font)
        self.date_3.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"max-height: 40px;\n"
"padding-bottom: 10px;")
        self.date_3.setObjectName("date_3")
        self.horizontalLayout_8.addWidget(self.date_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.weather_icon_3 = QtWidgets.QLabel(parent=self.widget_days_3)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.weather_icon_3.setFont(font)
        self.weather_icon_3.setStyleSheet("background: rgb(255, 255, 255, 0);")
        self.weather_icon_3.setText("")
        self.weather_icon_3.setPixmap(QtGui.QPixmap("../01d@2x.png"))
        self.weather_icon_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon_3.setObjectName("weather_icon_3")
        self.horizontalLayout_9.addWidget(self.weather_icon_3)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.temp_day_3 = QtWidgets.QLabel(parent=self.widget_days_3)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temp_day_3.setFont(font)
        self.temp_day_3.setStyleSheet("background: rgb(255, 255, 255, 0.6);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.temp_day_3.setObjectName("temp_day_3")
        self.verticalLayout_7.addWidget(self.temp_day_3)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.weather_3 = QtWidgets.QLabel(parent=self.widget_days_3)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weather_3.setFont(font)
        self.weather_3.setStyleSheet("background: rgb(255, 255, 255, 0);\n"
"max-height: 30px;\n"
"color: rgb(255, 255, 255);\n"
"font: 15px;\n"
"")
        self.weather_3.setObjectName("weather_3")
        self.verticalLayout_8.addWidget(self.weather_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        self.horizontalLayout.addWidget(self.widget_days_3)
        self.widget_days_4 = QtWidgets.QWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.widget_days_4.setFont(font)
        self.widget_days_4.setStyleSheet("border-radius: 8px;\n"
"background: rgb(115, 115, 173);\n"
"")
        self.widget_days_4.setObjectName("widget_days_4")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.widget_days_4)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, -1, -1, 70)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.day_of_week_4 = QtWidgets.QLabel(parent=self.widget_days_4)
        self.day_of_week_4.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-right-radius: 0px;\n"
"border-bottom-right-radius: 0px;\n"
"max-height: 50px;\n"
"font-size: 20px;\n"
"font: bold;")
        self.day_of_week_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.day_of_week_4.setObjectName("day_of_week_4")
        self.horizontalLayout_10.addWidget(self.day_of_week_4)
        self.date_4 = QtWidgets.QLabel(parent=self.widget_days_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.date_4.setFont(font)
        self.date_4.setStyleSheet("background: rgb(255, 255, 255, 0.8);\n"
"border-top-left-radius: 0px;\n"
"border-bottom-left-radius: 0px;\n"
"max-height: 40px;\n"
"padding-bottom: 10px;")
        self.date_4.setObjectName("date_4")
        self.horizontalLayout_10.addWidget(self.date_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.weather_icon_4 = QtWidgets.QLabel(parent=self.widget_days_4)
        font = QtGui.QFont()
        font.setPointSize(1)
        self.weather_icon_4.setFont(font)
        self.weather_icon_4.setStyleSheet("background: rgb(255, 255, 255, 0);")
        self.weather_icon_4.setText("")
        self.weather_icon_4.setPixmap(QtGui.QPixmap("../01d@2x.png"))
        self.weather_icon_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.weather_icon_4.setObjectName("weather_icon_4")
        self.horizontalLayout_11.addWidget(self.weather_icon_4)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.temp_day_4 = QtWidgets.QLabel(parent=self.widget_days_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.temp_day_4.setFont(font)
        self.temp_day_4.setStyleSheet("background: rgb(255, 255, 255, 0.6);\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.temp_day_4.setObjectName("temp_day_4")
        self.verticalLayout_10.addWidget(self.temp_day_4)
        self.horizontalLayout_11.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.weather_4 = QtWidgets.QLabel(parent=self.widget_days_4)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.weather_4.setFont(font)
        self.weather_4.setStyleSheet("background: rgb(255, 255, 255, 0);\n"
"max-height: 30px;\n"
"color: rgb(255, 255, 255);\n"
"font: 15px;\n"
"")
        self.weather_4.setObjectName("weather_4")
        self.verticalLayout_11.addWidget(self.weather_4)
        self.horizontalLayout_12.addLayout(self.verticalLayout_11)
        self.horizontalLayout.addWidget(self.widget_days_4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.city.setText(_translate("MainWindow", "Погода в Москве"))
        self.temp.setText(_translate("MainWindow", "+6*"))
        self.weather.setText(_translate("MainWindow", "Ясно"))
        self.temp_like.setText(_translate("MainWindow", "Ощущается как +3*"))
        self.wind.setText(_translate("MainWindow", "2,5 мс, СВ"))
        self.humidity.setText(_translate("MainWindow", "76%"))
        self.pressure.setText(_translate("MainWindow", "750 мм рт. ст."))
        self.day_of_week_1.setText(_translate("MainWindow", "Вторник"))
        self.date_1.setText(_translate("MainWindow", "29 окт"))
        self.temp_day_1.setText(_translate("MainWindow", "+6*"))
        self.weather_1.setText(_translate("MainWindow", "Малооблачно"))
        self.day_of_week_2.setText(_translate("MainWindow", "Среда"))
        self.date_2.setText(_translate("MainWindow", "30 окт"))
        self.temp_day_2.setText(_translate("MainWindow", "+8*"))
        self.weather_2.setText(_translate("MainWindow", "Малооблачно"))
        self.day_of_week_3.setText(_translate("MainWindow", "Четверг"))
        self.date_3.setText(_translate("MainWindow", "31 окт"))
        self.temp_day_3.setText(_translate("MainWindow", "+6*"))
        self.weather_3.setText(_translate("MainWindow", "Малооблачно"))
        self.day_of_week_4.setText(_translate("MainWindow", "Пятница"))
        self.date_4.setText(_translate("MainWindow", "1 ноя"))
        self.temp_day_4.setText(_translate("MainWindow", "+6*"))
        self.weather_4.setText(_translate("MainWindow", "Малооблачно"))
